---
 - name: install apache using compose
   hosts: msr1
   roles:
    - api/apache

 - name: install couchdb using compose
   hosts: msr2
   roles:
    - api/couchdb

 - name: install docker
   hosts: atul1
   roles: common/docker

 - name: install nodejs
   hosts: atul1
   roles: common/node
