version: '2'
services:
    apache2:
        image: webdevops/apache:latest
        args:
            - PHP_SOCKET=php:9000
        volumes:
            - ./msr/www:/var/www/html
        ports:
            - 80:80
            - 443:443
