---
  - name: create compose path
    file:
     path: /home/ubuntu/
     state: directory
     owner: ubuntu
     group: ubuntu

  - name: copy compose file
    template: src=docker-compose.yml.j2 dest=/home/ubuntu/docker-compose.yml

  - name: running compose file
    command: docker-compose up -d
    args:
      chdir: /home/ubuntu/
